# Site
name: AkuNgeblog
description: Berbagi Kebaikan & Motivasi
meta_description: "Berbagi Kebaikan & Motivasi"
logo: 'assets/images/logo-akungeblog.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
permalink: /:title/
email: 'boxsurel@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Front Matter SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/5.jpg
      
# Authors
authors:
  irfnrdh:
    name: irfnrdh
    display_name: irfnrdh
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  maverick:
    name: maverick
    display_name: maverick
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag  

  
# Archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

permalinks:
  year: '/archives/year/:year/'
  month: '/archives/month/:year-:month/'
  tag: '/archives/tag/:name/'

# Tagline
tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

ignored_tags: [tags,to,ignore]
tag_permalink_style: pretty

tag_page_data:
  sitemap: false


# Other
markdown: kramdown
highlighter: rouge

#optimization
#compress.html
compress_html:
  #clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

