# Site
name: AkuNgeblog
description: Berbagi Kebaikan & Motivasi
meta_description: "Berbagi Kebaikan & Motivasi"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 6
baseurl: 
permalink: /:title/
email: 'boxsurel@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Settings
production: false
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

# Front Matter SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/5.jpg
      

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag  



  
# Archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

permalinks:
  year: '/archives/year/:year/'
  month: '/archives/month/:year-:month/'
  tag: '/archives/tag/:name/'

jekyll-archives:
  enabled:
    - categories
  layout: 'listing-posts'
  permalinks:
    category: '/category/:name/'

# CONTENT
exclude:
  - README.md
  - go.sh
  - CNAME


# Tagline
tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

ignored_tags: [tags,to,ignore]
tag_permalink_style: pretty

tag_page_data:
  sitemap: false


# Other
markdown: kramdown
highlighter: rouge

#optimization
#compress.html
compress_html:
  #clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

